destinations:
  - id: username/app-prod
    alias: production
    registry: myRegistry
  - id: username/app-backup
    alias: backup
    registry: someRegistry
  - id: username/app-staging
    alias: staging
    registry: aRegistry
  - id: username/app-bob
    alias: bob
    registry: bobsspecialregistry.com

resources:
  - id: db
    image: nanobox/mysql
    options:
      foo: bar
      baz: qux
  - id: queue
    image: nanobox/redis

services:
  - id: web
    containers:
      - id: nginx
        image: Dockerfile.nginx
      - id: app
        image: Dockerfile.app
    http_port: 8080
    force_ssl: true
    health_check: /health
    routes:
      - 'admin:'
      - '^/admin/'
    tcp:
      - 5555:5555
    udp:
      - 9654:10000
  - id: worker
    containers:
      - id: app
        image: Dockerfile.worker
